=== Borichimitu/muaco/src/gabp/resources/program.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="program">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="parameters" name="parameters" />
        <xs:element type="xs:string" name="inputSet" />
        <xs:element type="xs:string" name="outputSet" />
        <xs:element type="group" name="group" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="parameters">
    <xs:annotation>
      <xs:documentation>
        GA parameters
      </xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="fixedOutput" type="xs:boolean" />
      <xs:element name="populationSize" type="xs:positiveInteger" />
      <xs:element name="desiredFitness" type="xs:double" />
      <xs:element name="stateNumber" type="xs:positiveInteger" />
      <xs:element name="partStay" type="xs:double" />
      <xs:element name="timeSmallMutation" type="xs:positiveInteger" />
      <xs:element name="timeBigMutation" type="xs:positiveInteger" />
      <xs:element name="mutationProbability" type="xs:double" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="group">
    <xs:sequence>
      <xs:element name="formulas" type="formulas" minOccurs="0"/>
      <xs:element name="tests" type="tests" minOccurs="0"/>
      <xs:element name="negativeTests" type="negativeTests" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="formulas">
    <xs:annotation>
      <xs:documentation>
        LTL formulas.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="ltl" type="xs:string" maxOccurs="unbounded"  minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tests">
    <xs:annotation>
      <xs:documentation>
        Tests group.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="test" type="test" maxOccurs="unbounded"  minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="test">
    <xs:annotation>
      <xs:documentation>
        Single test.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="input" type="xs:string"/>
      <xs:element name="output" type="xs:string"/>
      <xs:element name="ptest" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="negativeTests">
    <xs:annotation>
      <xs:documentation>
        Disabled Tests group.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="ntest" type="xs:string" maxOccurs="unbounded"  minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Borichimitu/muaco/experiments/clock/scenarios/ga/clock.xml
<program xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation = "resources/program.xsd">

    <parameters>
        <fixedOutput>true</fixedOutput>
        <populationSize>137</populationSize>
        <desiredFitness>0.0075</desiredFitness>
        <stateNumber>6</stateNumber>
        <partStay>0.47</partStay>
        <timeSmallMutation>286</timeSmallMutation>
        <timeBigMutation>255</timeBigMutation>
        <mutationProbability>0.08</mutationProbability>
    </parameters>

    <inputSet>A, T, H, M, T [!x1 &amp; !x2], T [x1 &amp; !x2], T [x2 &amp; !x1]</inputSet>
    <outputSet>z1, z2, z3, z4, z5, z6, z7</outputSet>

    <group>
        <tests>
        <test><ptest>T/z5; T/z5; T/z5; T/z5</ptest></test>
	<test><ptest>H/z1; H/z1; H/z1; H/z1</ptest></test>
	<test><ptest>M/z2; M/z2; M/z2; M/z2</ptest></test>
	<test><ptest>T/z5; M/z2; H/z1; T/z5; T/z5; T/z5; M/z2; T/z5; H/z1; H/z1; T/z5; M/z2</ptest></test>
	<test><ptest>A; T/z5; M/z4; H/z3; T/z5; T/z5; T/z5; M/z4; T/z5; H/z3; H/z3; T/z5; M/z4</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; M/z2; H/z1; T [!x1 &amp; !x2]/z5; T [!x1 &amp; !x2]/z5; T [!x1 &amp; !x2]/z5; M/z2; T [!x1 &amp; !x2]/z5; H/z1; H/z1; T [!x1 &amp; !x2]/z5; M/z2</ptest></test>
	<test><ptest>A; T/z5; T/z5; T/z5; T/z5</ptest></test>
	<test><ptest>A; H/z3; H/z3; H/z3; H/z3</ptest></test>
	<test><ptest>A; M/z4; M/z4; M/z4; M/z4</ptest></test>
	<test><ptest>A; T/z5; T/z5; M/z4; H/z3; T/z5; T/z5</ptest></test>
	<test><ptest>A; A; H/z1; H/z1; H/z1; H/z1</ptest></test>
	<test><ptest>A; A; M/z2; M/z2; M/z2; M/z2</ptest></test>
	<test><ptest>A; A; A/z7; T/z5; T/z5; T/z5; T/z5</ptest></test>
	<test><ptest>A; A; A/z7; H/z1; H/z1; H/z1; H/z1</ptest></test>
	<test><ptest>A; A; A/z7; M/z2; M/z2; M/z2; M/z2</ptest></test>
	<test><ptest>A; A; A/z7; A; T/z5</ptest></test>
	<test><ptest>A; A; A/z7; A; T/z5; T/z5; T/z5; T/z5</ptest></test>
	<test><ptest>A; A; A/z7; A; H/z3</ptest></test>
	<test><ptest>A; A; A/z7; A; H/z3; H/z3; H/z3; H/z3</ptest></test>
	<test><ptest>A; A; A/z7; A; M/z4</ptest></test>
	<test><ptest>A; A; A/z7; A; M/z4; M/z4; M/z4; M/z4</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [!x1 &amp; !x2]/z5; T [!x1 &amp; !x2]/z5</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7; A/z7; H/z1</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7; A/z7; M/z2</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7; A/z7; T/z5</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7; H/z1</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7; M/z2</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7; T [!x1 &amp; !x2]/z5</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7; A/z7; A; H/z3</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7; A/z7; A; M/z4</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7; A/z7; A; T/z5</ptest></test>
	<test><ptest>A; A; T [x1 &amp; !x2]/z5,z6</ptest></test>
	<test><ptest>A; A; T [x2 &amp; !x1]/z5,z7</ptest></test>
	<test><ptest>A; A; T [x1 &amp; !x2]/z5,z6; T [x2 &amp; !x1]/z5,z7</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5; T [x1 &amp; !x2]/z5,z6; A/z7; A; T/z5</ptest></test>
	<test><ptest>A; A; T [!x1 &amp; !x2]/z5</ptest></test>
        </tests>
   </group>
</program>

=== Borichimitu/muaco/experiments/elevator/scenarios/ga/elevator.xml
<program xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation = "resources/program.xsd">

    <!--
        e11 - открыть двери
        e12 - закрыть двери
        e2 - успешное отктрытие или закрытие дверей
        e3 - припядсвие мешает закрыть двери
        e4 - двери сломались
        z1/z2 запуск открытия/закрытия дверей
        z3 - звонок в аварийную службу
    -->

    <parameters>
        <fixedOutput>true</fixedOutput>
        <populationSize>137</populationSize>
        <desiredFitness>0.0075</desiredFitness>
        <stateNumber>6</stateNumber>
        <partStay>0.47</partStay>
        <timeSmallMutation>286</timeSmallMutation>
        <timeBigMutation>255</timeBigMutation>
        <mutationProbability>0.08</mutationProbability>
    </parameters>

    <inputSet>e11, e12, e2, e3, e4</inputSet>
    <outputSet>z1, z2, z3</outputSet>

    <group>
        <tests>
            <test>
                <input>e11, e2, e12, e2</input>
                <output>z1, z2</output>
                <ptest>e11/z1; e2; e12/z2; e2</ptest>
            </test>
            <test>
                <input>e11, e2, e12, e2, e11, e2, e12, e2</input>
                <output>z1, z2, z1, z2</output>
                <ptest>e11/z1; e2; e12/z2; e2; e11/z1; e2; e12/z2; e2</ptest>
            </test>
            <test>
                <input>e11, e2, e12, e3, e2, e12, e2</input>
                <output>z1, z2, z1, z2</output>
                <ptest>e11/z1; e2; e12/z2; e3/z1; e2; e12/z2; e2</ptest>
            </test>
            <test>
                <input>e11, e2, e12, e2, e11, e2, e12, e3, e2, e12, e2</input>
                <output>z1, z2, z1, z2, z1, z2</output>
                <ptest>e11/z1; e2; e12/z2; e2; e11/z1; e2; e12/z2; e3/z1; e2; e12/z2; e2</ptest>
            </test>
            <test>
                <input>e11, e2, e12, e3, e2, e12, e3, e2, e12, e2</input>
                <output>z1, z2, z1, z2, z1, z2</output>
                <ptest>e11/z1; e2; e12/z2; e3/z1; e2; e12/z2; e3/z1; e2; e12/z2; e2</ptest>
            </test>
            <test>
                <input>e11, e4</input>
                <output>z1, z3</output>
                <ptest>e11/z1; e4/z3</ptest>
            </test>
            <test>
                <input>e11, e2, e12, e4</input>
                <output>z1, z2, z3</output>
                <ptest>e11/z1; e2; e12/z2; e4/z3</ptest>
            </test>
            <test>
                <input>e11, e2, e12, e2, e11, e4</input>
                <output>z1, z2, z1, z3</output>
                <ptest>e11/z1; e2; e12/z2; e2; e11/z1; e4/z3</ptest>
            </test>
            <test>
                <input>e11, e2, e12, e3, e4</input>
                <output>z1, z2, z1, z3</output>
                <ptest>e11/z1; e2; e12/z2; e3/z1; e4/z3</ptest>
            </test>
        </tests>
    </group>
</program>
